[package]
name = "question_10"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = "0.12.4"
image = "0.25.0"
num = "0.4.1"
num_cpus = "1.16.0"
threadpool = "1.8.1"
